safe_alias m 'mise'
safe_alias mu 'mise use'
safe_alias mug 'mise use -g'
safe_alias mx 'mise exec --'
safe_alias mr 'mise run'
safe_alias mi 'mise install'
safe_alias mls 'mise ls'
safe_alias mlsr 'mise ls --missing'
safe_alias mc 'mise current'
safe_alias mo 'mise outdated'
safe_alias mob 'mise outdated --bump'
safe_alias mup 'mise upgrade'
safe_alias mp 'mise prune'
safe_alias mtr 'mise trust'
safe_alias mw 'mise where'
safe_alias ms 'mise settings'
