safe_alias gor 'go run .'
safe_alias gob 'go build .'
safe_alias got 'go test ./...'
safe_alias gotr 'go test -race ./...'
safe_alias gotv 'go test -v ./...'
safe_alias gom 'go mod tidy'
safe_alias gog 'go get'
safe_alias goi 'go install'
safe_alias gof 'go fmt ./...'
