# NPM
safe_alias nrl 'npm run lint'
safe_alias nrd 'npm run dev'
safe_alias nrt 'npm run test'
safe_alias nrb 'npm run build'
safe_alias npr 'npm run'
safe_alias npo 'npm outdated'
safe_alias npu 'npm update'
safe_alias npis 'npm install --save'
safe_alias npid 'npm install --save-dev'
safe_alias nrlf 'npm run lint-fix'
safe_alias nrtc 'npm run test:ci'

# PNPM
safe_alias mm 'pnpm'
safe_alias mml 'pnpm lint'
safe_alias mmd 'pnpm dev'
safe_alias mmt 'pnpm test'
safe_alias mmb 'pnpm build'
safe_alias mms 'pnpm start'
safe_alias mmo 'pnpm outdated'
safe_alias mmu 'pnpm update'
