# Docker
safe_alias d 'docker'
safe_alias di 'docker images'
safe_alias dr 'docker run'
safe_alias drm 'docker run --rm'
safe_alias drmi 'docker run --rm -it'
safe_alias drmia 'docker run --rm -it -v $(pwd):/app'
safe_alias db 'docker build -t'

# Docker Compose
safe_alias dcm 'docker-compose'
safe_alias dcb 'docker-compose build'
safe_alias dce 'docker-compose exec'
safe_alias dcu 'docker-compose up'
safe_alias dcuf 'docker-compose up --force-recreate'
safe_alias dcud 'docker-compose up -d'
safe_alias dcudf 'docker-compose up -d --force-recreate'
safe_alias dcs 'docker-compose stop'
safe_alias dcp 'docker-compose ps'
safe_alias dcrm 'docker-compose run --rm'
